# -*- coding: utf-8 -*-
"""OnePager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Co8Op1TihyUSAX5Eq4buHeHzO19j0Hm4
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import folium
from folium import CircleMarker
from streamlit_folium import st_folium
from branca.colormap import LinearColormap

st.title("OXXO: Descubriendo las Tiendas del Futuro ")

df = pd.read_csv("df_binary_train.csv")
df_numeric = pd.read_csv("df_train_numeric.csv")

st.header("Ubicación Geográfica de las Tiendas")
st.markdown("""
Este mapa muestra la distribución actual de tiendas. Observamos mayor concentración en zonas urbanas  con las zonas con mayor concentración tienden a ser de nivel socioeconómico **C**, mientras que las zonas tipo **A** presentan una menor cobertura.

Esto sugiere una oportunidad de expansión en zonas donde la cobertura es baja.
""")
mexico_map = folium.Map(location=[25.0, -101.5], zoom_start=7)
color_mapping = {
    'A': 'darkgreen',
    'AB': 'green',
    'B': 'lime',
    'BC': 'lightgreen',
    'C': 'yellow',
    'CD': 'orange',
    'D': 'red'
}

for lat, lng, nivel in zip(df['LATITUD_NUM'], df['LONGITUD_NUM'], df['NIVELSOCIOECONOMICO_DES']):
    color = color_mapping.get(nivel, '#808080')
    folium.CircleMarker(
        location=[lat, lng],
        radius=5,
        color=color,
        fill=True,
        fill_color=color,
        fill_opacity=0.7,
        popup=f"Nivel: {nivel}"
    ).add_to(mexico_map)

# Add custom legend as HTML
legend_html = '''
<div style="
    position: fixed;
    bottom: 10px;
    left: 10px;
    width: 110px;
    border: 1px solid grey;
    z-index: 9999;
    font-size: 10px;
    background-color: white;
    padding: 5px;
    line-height: 1.3;
    ">
    <div style="font-weight: bold; text-align: center; margin-bottom: 3px;">Socioeconomic Level</div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: darkgreen; margin-right: 5px;"></div>
        <span>A</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: green; margin-right: 5px;"></div>
        <span>AB</span>
    </div>
    <div style="width: 12px; height: 12px; background-color: lime; margin-right: 5px;"></div>
        <span>B</span>
    <div style="width: 12px; height: 12px; background-color: lightgreen; margin-right: 5px;"></div>
        <span>BC</span>
    <div style="width: 12px; height: 12px; background-color: yellow; margin-right: 5px;"></div>
        <span>C</span>
    <div style="width: 12px; height: 12px; background-color: orange; margin-right: 5px;"></div>
        <span>CD</span>
    <div style="width: 12px; height: 12px; background-color: red; margin-right: 5px;"></div>
        <span>D</span>
</div>
'''
mexico_map.get_root().html.add_child(folium.Element(legend_html))

st_data = st_folium(mexico_map, width=700, height=500)

st.header("Tipos de Tienda por Nivel Socioeconómico y Entorno")
st.markdown("""
Aquí visualizamos los diferentes tipos de tiendas y cómo se distribuyen según el nivel socioeconómico y el entorno.

Los segmentos más comunes son , con una mayor presencia en entornos con niveles socioeconómico de **C y D**.

Esto indica una tendencia a adaptar el tipo de tienda a las condiciones del entorno.
""")

st.header("Distribución de Éxito por Nivel Socioeconómico")
levels = df['NIVELSOCIOECONOMICO_DES'].unique()

selected_level = st.selectbox("Selecciona el nivel socioeconómico para visualizar:", sorted(levels))
subset = df[df['NIVELSOCIOECONOMICO_DES'] == level]
counts = subset['labelExito'].value_counts()

total = counts.sum()
successes = counts.get(1, 0)
failures = counts.get(0, 0)
fig, ax = plt.subplots()
ax.pie(counts, labels=counts.index, autopct='%1.2f%%', startangle=90)
ax.set_title(f'Nivel Socioeconómico: {level}\nÉxito (1): {successes} | Fracaso (0): {failures} | Total: {total}')
ax.axis('equal')
st.pyplot(fig)

st.header("Tasa Promedio de Cumplimiento por Variable")
st.markdown(""" """)
group_options = {
    "Nivel Socioeconómico": "NIVELSOCIOECONOMICO_DES",
    "Entorno": "ENTORNO_DES",
    "Segmento Maestro": "SEGMENTO_MAESTRO_DESC"
}

selected_group = st.selectbox("Selecciona una variable para agrupar:", list(group_options.keys()))

group_column = group_options[selected_group]

avg_values = df_numeric.groupby(group_column)["tasa_cumplimiento"].mean().sort_values()

fig, ax = plt.subplots()
avg_values.plot(kind='bar', color='blue', ax=ax)
ax.set_title(f'Promedio de Tasa de Cumplimiento por {selected_group}')
ax.set_ylabel('Tasa de Cumplimiento Promedio')
plt.xticks(rotation=45)

st.header("Mapa Binario de Éxito por Tienda")

color_mapping = {1: 'green', 0: 'red'}
mapa_exito = folium.Map(location=[25.0, -101.5], zoom_start=6)

for lat, lng, exito in zip(df['LATITUD_NUM'], df['LONGITUD_NUM'], df['labelExito']):
    folium.CircleMarker(
        location=[lat, lng],
        radius=5,
        color=color_mapping.get(exito, 'gray'),
        fill=True,
        fill_color=color_mapping.get(exito, 'gray'),
        fill_opacity=0.7,
        popup=f"Éxito: {exito}"
    ).add_to(mapa_exito)

# Agregar leyenda manualmente
legend_html = '''
<div style="
    position: fixed;
    bottom: 10px;
    left: 10px;
    width: 110px;
    border: 1px solid grey;
    z-index: 9999;
    font-size: 10px;
    background-color: white;
    padding: 5px;
    line-height: 1.3;
    ">
    <div style="font-weight: bold; text-align: center; margin-bottom: 3px;">Socioeconomic Level</div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: darkgreen; margin-right: 5px;"></div>
        <span>A</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: green; margin-right: 5px;"></div>
        <span>AB</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: lime; margin-right: 5px;"></div>
        <span>B</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: lightgreen; margin-right: 5px;"></div>
        <span>BC</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: yellow; margin-right: 5px;"></div>
        <span>C</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: orange; margin-right: 5px;"></div>
        <span>CD</span>
    </div>
    <div style="display: flex; align-items: center; margin: 1px 0;">
        <div style="width: 12px; height: 12px; background-color: blue; margin-right: 5px;"></div>
        <span>D</span>
    </div>
</div>
'''
mexico_map.get_root().html.add_child(folium.Element(legend_html))

st_folium(mapa_exito, width=700)

